export const Workflowfields = {
        id: '',
        productType: null,
        sourceCardId: '',
        destinationCardId: '',
        siteName: '',
        code1141: '',
        sourceSneId: null,
        sourceCardMtosiName: '',
        sourceCardName: '',
        sourceSlot: '',
        sourceCardLevel: '',
        sourceCardType: '',
        sourceCardUsedPortsCount: '',
        destinationSneId: '',
        destinationCardMtosiName: '',
        destinationCardName: '',
        destinationSlot: '',
        destinationCardLevel: '',
        destinationCardType: '',
        destinationCardFreePortCount: '',
        workflowstatus: 0,
        cpNumber: '',
        projectId: '',
        sourceNoOfService: '',
        destinationNoOfService: '',
        cardInfillSavePlanRequest: null,
        free: '',
        rackId: '',
        rackPosition: '',
        sourceSatelliteShelf: '',
        destinationSatelliteShelf: '',
        sourcePortSpeed : '',
        destinationPortSpeed : ''
};
